name: invoice_app
description: Professional invoice generator app for freelancers
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_analytics: ^12.4.6
  firebase_crashlytics: ^5.2.7
  cupertino_icons: ^1.0.6
  google_fonts: ^8.2.1
  provider: ^6.1.2
  firebase_core: ^4.13.0
  firebase_auth: ^6.5.7
  cloud_firestore: ^6.8.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  pdf: ^3.13.0
  printing: ^5.15.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2
  uuid: ^4.6.0
  image_picker: ^1.0.7
  signature: ^6.4.0
  flutter_local_notifications: ^22.2.0
  timezone: ^0.11.1
  flutter_timezone: ^5.1.0
  in_app_review: ^2.0.12
  lottie: ^3.5.1
  flutter_colorpicker: ^1.1.0
  share_plus: ^11.0.0
  purchases_flutter: ^10.8.0
  purchases_ui_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  rename: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon_1024.png"
  remove_alpha_ios: true
  min_sdk_android: 21
  adaptive_icon_background: "assets/images/icon_adaptive_bg.png"
  adaptive_icon_foreground: "assets/images/icon_adaptive_fg.png"

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
