// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX4qT1AZZI4yxiBVIxVP_Yu3c-4889Jnw',
    appId: '1:817604946859:android:d29ccc9613083d43be40ee',
    messagingSenderId: '817604946859',
    projectId: 'invoice-app-flutter-072026',
    storageBucket: 'invoice-app-flutter-072026.firebasestorage.app',
  );
  // IMPORTANT: Download GoogleService-Info.plist from the Firebase console
  // (Project settings > Your apps > iOS > com.example.invoiceApp) and add it
  // to ios/Runner/ in Xcode. Then fill the values below from that file.

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTbPEu9wvNzxHIvWTcP5BTuWYin_UyQjU',
    appId: '1:817604946859:ios:534e71abf1d089e1be40ee',
    messagingSenderId: '817604946859',
    projectId: 'invoice-app-flutter-072026',
    storageBucket: 'invoice-app-flutter-072026.firebasestorage.app',
    iosBundleId: 'com.invoicemaker.app',
  );
}
